import com.kotori316.plugin.cf.CallVersionCheckFunctionTask
import com.kotori316.plugin.cf.CallVersionFunctionTask
import net.fabricmc.loom.api.processor.MinecraftJarProcessor
import net.fabricmc.loom.api.processor.ProcessorContext
import net.fabricmc.loom.api.processor.SpecContext

import java.nio.file.Files
import java.nio.file.Paths
import java.nio.file.StandardCopyOption

plugins {
    id("scala")
    id("maven-publish")
//    id 'fabric-loom' /*version "1.4-SNAPSHOT"*/
    alias(libs.plugins.loom)
    alias(libs.plugins.publish.all)
    alias(libs.plugins.cf)
}

base {
    archivesName = project.archives_base_name
}
version = project.mod_version
group = project.maven_group

repositories {
    maven {
        name = "Main"
        url = uri("https://maven.kotori316.com")
        content {
            includeVersion("org.typelevel", "cats-core_3", libs.versions.cats.get())
            includeVersion("org.typelevel", "cats-kernel_3", libs.versions.cats.get())
            includeVersion("org.typelevel", "cats-free_3", libs.versions.cats.get())
        }
    }
    maven {
        name = 'legacy-fabric'
        url = 'https://maven.legacyfabric.net'
    }
    // Fixed LWJGL on Linux
    maven {
        name = 'Babric'
        url = 'https://maven.glass-launcher.net/babric'
    }
    maven {
        url = "https://api.modrinth.com/maven"
    }
    maven {
        url 'https://btw-community.github.io/btw-mvn/'
    }
    mavenCentral() //For fastutil
}

def lwjglVersion = System.getProperty("os.name").toLowerCase().contains("mac") ? "2.9.1" : "2.9.0"

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "btw.community:mappings:1.0.3"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    // modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    include(api(group: "org.scala-lang", name: "scala3-library_3", version: libs.versions.scala3.get()))
    include(api(group: "org.scala-lang", name: "scala-library", version: libs.versions.scala2.get()))
    include(api(group: "org.typelevel", name: "cats-core_3", version: libs.versions.cats.get()))
    include(api(group: "org.typelevel", name: "cats-kernel_3", version: libs.versions.cats.get()))
    include(api(group: "org.typelevel", name: "cats-free_3", version: libs.versions.cats.get()))

    implementation 'net.fabricmc:fabric-loom:1.4-SNAPSHOT'

    implementation 'org.apache.logging.log4j:log4j-core:2.19.0'
    implementation 'org.apache.logging.log4j:log4j-api:2.19.0'

    implementation "org.lwjgl.lwjgl:lwjgl_util:${lwjglVersion}"
    implementation "org.lwjgl.lwjgl:lwjgl:${lwjglVersion}"
    implementation "org.lwjgl.lwjgl:lwjgl-platform:${lwjglVersion}"

    implementation fileTree(dir: "libs", include: "**.zip")

    implementation 'com.google.guava:guava:14.0.1'

    // This is what MC 1.6 uses
    implementation 'com.google.code.gson:gson:2.2.2'

    implementation group: 'it.unimi.dsi', name: 'fastutil', version: '8.5.12'

    implementation 'com.typesafe:config:1.4.5'
}

processResources {
    inputs.property("version", project.version)

    filesMatching("fabric.mod.json") {
        expand("version": project.version)
    }
}

java {
    withSourcesJar()
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archives_base_name}" }
    }
}

tasks.named("wrapper", Wrapper) {
    it.gradleVersion = "9.3.0"
}

tasks.withType(GenerateModuleMetadata).configureEach {
    enabled = false
}

tasks.remapJar.mustRunAfter(tasks.compileTestScala)

final boolean RELEASE_DEBUG = (System.getenv("RELEASE_DEBUG") ?: "true").toBoolean()

// configure the maven publication
publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifact(tasks.jar)
            artifactId = project.archives_base_name
            pom {
                name = project.archives_base_name
                description = "SLP for Minecraft with Fabric"
                url = project.url
                packaging = "jar"
                withXml {
                    List<String> notRequiredArtifacts = ["fabric-loader", "fabric-api"]
                    def pomNode = asNode() as Node
                    pomNode.dependencies."*".findAll() { Node node ->
                        def valueList = node.value() as NodeList
                        String artifactId = ((valueList.get(1) as Node).value() as NodeList).get(0)
                        if (notRequiredArtifacts.stream().anyMatch { artifactId.contains(it) }) {
                            node.parent().remove(node)
                        }
                    }
                }
            }
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        def u = project.findProperty("maven_username") as String ?: System.getenv("MAVEN_USERNAME") ?: ""
        def p = project.findProperty("maven_password") as String ?: System.getenv("MAVEN_PASSWORD") ?: ""
        if (u != "" && p != "" && !RELEASE_DEBUG) {
            maven {
                name = "kotori316-maven"
                // For users: Use https://maven.kotori316.com to get artifacts
                url = uri("https://maven2.kotori316.com/production/maven")
                credentials {
                    username = u
                    password = p
                }
            }
        }
        if (System.getenv("CI") == null) {
            maven {
                name = "MavenTestGCP"
                url = uri("gcs://kotori316-maven-test-storage/maven/")
            }
        }
    }
}

String createChangelog() {
    return """\
## Scalable Cat's Force Fabric

Provides scala language adapter to Fabric.

### Build dependencies:

- Scala ${libs.versions.scala2.get()}
- Scala3 ${libs.versions.scala3.get()}
- Cats Kernel ${libs.versions.cats.get()}
- Cats Core ${libs.versions.cats.get()}
- Cats Free ${libs.versions.cats.get()}
- Fabric Loader ${libs.versions.fabric.loader.get()}

### Repositry

${project.url}/tree/${project.branch}
"""
}

publishMods {
    dryRun = RELEASE_DEBUG
    type = STABLE
    file = provider { tasks.remapJar }.flatMap { it.archiveFile }
    additionalFiles = files(
            provider { tasks.jar }.flatMap { it.archiveFile },
            provider { tasks.sourcesJar }.flatMap { it.archiveFile },
    )
    modLoaders = ["fabric"]
    displayName = "${project.version}-fabric"
    changelog = createChangelog()

    def endVersion = "1.21.6"
    curseforge {
        accessToken = (project.findProperty("curseforge_additional-enchanted-miner_key") ?: System.getenv("CURSE_TOKEN") ?: "") as String
        projectId = "320926"
        minecraftVersionRange {
            start = libs.versions.minecraft.main.get()
            end = endVersion
        }
    }
    modrinth {
        accessToken = (project.findProperty("modrinthToken") ?: System.getenv("MODRINTH_TOKEN") ?: "") as String
        projectId = "zr0QMQMo"
        minecraftVersionRange {
            start = libs.versions.minecraft.main.get()
            end = endVersion
            includeSnapshots = false
        }
    }
    github {
        accessToken = (project.findProperty("githubToken") ?: System.getenv("REPO_TOKEN") ?: "") as String
        repository = "Kotori316/SLP-fabric"
        commitish = project.property("branch") as String
        tagName = "v${project.version}"
        displayName = "v${project.version}"
    }
}

tasks.register("registerVersion", CallVersionFunctionTask.class) {
    functionEndpoint = CallVersionFunctionTask.readVersionFunctionEndpoint(project)
    gameVersion = libs.versions.minecraft.main.get()
    platform = "fabric"
    platformVersion = libs.versions.fabric.loader.get()
    modName = "ScalableCatsForce-Fabric"
    changelog = createChangelog()
    homepage = "https://modrinth.com/mod/scalable-cats-force"
    isDryRun = RELEASE_DEBUG
}

tasks.register("checkReleaseVersion", CallVersionCheckFunctionTask.class) {
    gameVersion = libs.versions.minecraft.main.get()
    platform = "fabric"
    modName = "ScalableCatsForce-Fabric"
    version = project.version.toString()
    failIfExists = !RELEASE_DEBUG
}

loom {
    setIntermediaryUrl('https://maven.legacyfabric.net/net/legacyfabric/intermediary/%1$s/intermediary-%1$s-v2.jar');
    //accessWidenerPath = file('src/main/resources/<NAME>.accesswidener')
    addMinecraftJarProcessor(
            BTWJarReplacer, "BTWJarReplacer", projectDir.toString()
    )
    mods {
        flk {
            sourceSet sourceSets.main
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
}

configurations.all {
    resolutionStrategy {
        dependencySubstitution {
            substitute module('org.lwjgl.lwjgl:lwjgl_util:2.9.1-nightly-20130708-debug3') with {
                module("org.lwjgl.lwjgl:lwjgl_util:${lwjglVersion}")
            }
            substitute module('org.lwjgl.lwjgl:lwjgl:2.9.1-nightly-20130708-debug3') with {
                module("org.lwjgl.lwjgl:lwjgl:${lwjglVersion}")
            }
        }
        force "org.lwjgl.lwjgl:lwjgl-platform:${lwjglVersion}"
    }
}

jar {
    from sourceSets.main.output.resourcesDir
    from sourceSets.main.output.classesDirs
    from("LICENSE") {
        rename { "${it}_${project.archivesBaseName}"}
    }
}

tasks.register('copyBtwJar', Copy) {
    def depInter = dependencies.create("maven.modrinth:btwce:${project.btw_version}:intermediary")
    def depDoc = dependencies.create("maven.modrinth:btwce:${project.btw_version}:javadoc")
    def depMappings = dependencies.create("btw.community:mappings:1.0.3")

    def config = configurations.detachedConfiguration(depInter, depDoc, depMappings)
    config.transitive = false

    from config
    into file("build_BTW/tmp/BTW_dev")

    rename { String fileName ->
        if (fileName.contains("javadoc")) {
            return "BTW-CE-Intermediary-javadoc.jar"
        }
        if (fileName.contains("mappings")) {
            return "BTW-CE-mappings.jar"
        }
        return "BTW-CE-Intermediary.jar"
    }
}

class BTWJarReplacer implements MinecraftJarProcessor<Spec> {
    String name
    String path

    @javax.inject.Inject
    BTWJarReplacer(String name, String path) {
        this.name = name
        this.path = path
    }

    @Override
    Spec buildSpec(SpecContext context) {
        return new Spec(path)
    }

    @Override
    void processJar(java.nio.file.Path jar, Spec spec, ProcessorContext context) throws IOException {
        // Replace the Minecraft jar with the custom one from BTW_dev.
        // This is just a straight up file replacement, no remapping or anything.
        if (!Files.exists(Paths.get(path, "build_BTW/BTW_dev/BTW_dev.zip")) && !Files.exists(Paths.get(path, "build_BTW/BTW_dev/BTW_dev-javadoc.jar"))) {
            // Print a warning if the BTW_dev zip doesn't exist.
            System.err.println("BTW_dev zip not found, skipping BTWJarReplacer")
        } else {
            System.out.println("BTW_dev zip found, replacing Minecraft jar with BTW_dev jar.")
            Files.copy(Paths.get(path, "build_BTW/BTW_dev/BTW_dev.zip"), jar, StandardCopyOption.REPLACE_EXISTING)
            // Add Javadocs
            Files.copy(Paths.get(path, "build_BTW/BTW_dev/BTW_dev-javadoc.jar"), jar.resolveSibling(jar.getFileName().toString().replace(".jar", "-javadoc.jar")), StandardCopyOption.REPLACE_EXISTING)
        }
    }

    @Override
    String getName() {
        return name
    }

    class Spec implements MinecraftJarProcessor.Spec {
        String path

        Spec(String path) {
            this.path = path
        }

        @Override
        int hashCode() {
            if (!Files.exists(Paths.get(path, "build_BTW/BTW_dev/BTW_dev.zip"))) {
                return name.hashCode()
            } else {
                return Files.getLastModifiedTime(Paths.get(path, "build_BTW/BTW_dev/BTW_dev.zip")).hashCode() ^ name.hashCode()
            }
        }
    }

}