# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Mod Properties
# Remember to change version in example property.
mod_version=3.1.8
maven_group=com.kotori316
archives_base_name=scalable-cats-force-fabric
url=https://github.com/Kotori316/SLP-fabric
# Other
branch=scala3

minecraft_version = 1.6.4
btw_version = 3.0.0
yarn_mappings = 1.6.4+build.420
loader_version = 0.14.19